### ISSUE TITLE
allow to force Hindsight to shutdown when an essential sandbox dies

### ISSUE THREAD

**Issue by bbinet** [trink/hindsight#21]
I need something equivalent to the `can_exit` config in Heka.

For example, if the main sandbox of my Hindsight setup dies (for example because of a permission issue, or because my disk is full), I would like Hindsight to shutdown.
Does Hindsight support this use case?

Ideally Hindsight could try to restart the failing sandbox a configurable number of times, and if the sandbox is still dying, Hindsight would completely shutdown.

What do you think?

**Comment by bbinet** [comment]
Something equivalent to Heka behavior would be great: http://hekad.readthedocs.org/en/latest/config/index.html?highlight=can_exit#configuring-restarting-behavior

**Comment by trink** [comment]
Hindsight is designed to always be running (eventually it will be daemonized).  It should be thought of as a service waiting for a job to be submitted (that is why it can run without any plugins).  A job (plugin) failure should never cause the service to shut-down since it may be running other peoples jobs in addition to yours.  This type of functionality would not be part of the infrastructure itself but could be bolted on much like the pruning/file cleanup is (you could monitor for sandbox terminations, restart them as desired or shutdown the HS process).

**Comment by bbinet** [comment]
Ok, I see.
How would you technically monitor the sandbox terminations?

**Comment by trink** [comment]
Currently you could monitor the HS error log output (stderr).  There are some open options/todo's around that i.e.,possibly generating Heka protobuf message and dumping them on the input queue, or creating a dedicated input to manage them, etc

You could also monitor the hindsight.tsv (stats) file but that is only updated once a minute so it would be a a little less timely.

**Comment by bbinet** [comment]
Once a minute is fine with me, but do you know a sandbox has been terminated by monitoring hindsight.tsv? This information is not available in the tsv file, isn't it?

**Comment by trink** [comment]
The fact that it is not there is exactly how you would detect it.

**Comment by bbinet** [comment]
Ok, I see.
Thanks.
